import one from './image/one-min.png'
import two from './image/two-min.png'
import three from './image/three-min.png'
import prem from './image/prem-min.png'

function getRandomNumber(min, max) {
  return Math.round(Math.random() * (max - min) + min)
}

export const data = [
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 50,
      top: 50,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 550,
      top: 250,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 500,
      top: 100,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 300,
      top: 200,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    margin: 'auto',
    diameter: 30,
    position: {
      left: 200,
      top: 300,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 450,
      top: 300,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 50,
      top: 300,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 600,
      top: 200,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: two,
    imgSize: '28px',
    imgSizeW: '28px',
    diameter: 50,
    margin: 'auto',
    position: {
      left: 450,
      top: 0,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'white',
    backgroundImage: three,
    imgSize: '28px',
    imgSizeW: '16px',
    diameter: 50,
    margin: 'auto',
    position: {
      left: 200,
      top: 20,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
  {
    color: 'blue',
    backgroundImage: prem,
    diameter: 50,
    position: {
      left: 500,
      top: 250,
    },
    interval: 1,
    distance: getRandomNumber(100, 200),
    step: getRandomNumber(20, 60),
  },
]

export const dataMobile = [
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 100,
      top: 10,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 160,
      top: 100,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 450,
      top: 100,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 230,
      top: 200,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'white',
    backgroundImage: one,
    imgSize: '11px',
    imgSizeW: '11px',
    diameter: 30,
    margin: 'auto',
    position: {
      left: 450,
      top: 250,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'white',
    backgroundImage: two,
    imgSize: '28px',
    imgSizeW: '28px',
    diameter: 50,
    margin: 'auto',
    position: {
      left: 100,
      top: 150,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'white',
    backgroundImage: three,
    imgSize: '28px',
    imgSizeW: '16px',
    diameter: 50,
    margin: 'auto',
    position: {
      left: 200,
      top: 20,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
  {
    color: 'blue',
    backgroundImage: prem,
    diameter: 50,
    position: {
      left: 50,
      top: 210,
    },
    interval: 1,
    distance: 40,
    step: 40,
  },
]
